<?php
/**
 * @package MRSync for vBulletin
 * @author Jose Argudo Blanco
 * @website www.consultorpc.com
 * @email jose@consultorpc.com
 * @version 1.0.0
 * @date 26/08/11
 * @copyright ConsultorPC
 * @license Proprietary
**/

require_once('./global.php');
require_once(DIR . '/includes/mrsync/mrsyncInit.php');

 // Look for params or set a default
 // 'do' is the default param name generated by vBulletin print_form_header function
if ( empty($_REQUEST['do']) ) {
    $_REQUEST['do'] = 'showSettings';
}

switch( $_REQUEST['do'] ) {
    case 'save':
        try {           
            $mrsyncSettingsController->showSettings( $mrsyncSettingsController->saveAction( $_REQUEST ) );        
        } catch ( Exception $e ) {
            echo '(mrsync_settings_admin.php) An error has been found in save case: ' . $e->getMessage();
        }        
        break;
    case 'showSettings':
    default:
        try {  
            $mrsyncSettingsController->showSettings($_REQUEST['message']);
        } catch ( Exception $e ) {
            echo '(mrsync_settings_admin.php) An error has been found in showSettings case: ' . $e->getMessage();
        }              
}